# Generated by Django 5.0.6 on 2025-01-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classID', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Data',
            fields=[
                ('facultyID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('facultyName', models.CharField(max_length=255)),
                ('facultyDesignation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('assigned_classes', models.ManyToManyField(related_name='faculty_classes', to='administrator.classroom')),
            ],
        ),
    ]
