# Generated by Django 5.0.6 on 2025-01-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty_Data',
            new_name='FacultyData',
        ),
    ]
